export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS:     'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED:      'EMAIL_NOT_VERIFIED',
  ACCOUNT_DISABLED:        'ACCOUNT_DISABLED',
  TOKEN_EXPIRED:           'TOKEN_EXPIRED',
  TOKEN_INVALID:           'TOKEN_INVALID',
  TOKEN_REUSE_DETECTED:    'TOKEN_REUSE_DETECTED',
  SESSION_NOT_FOUND:       'SESSION_NOT_FOUND',

  // User
  EMAIL_ALREADY_EXISTS:    'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  USER_NOT_FOUND:          'USER_NOT_FOUND',
  INCORRECT_PASSWORD:      'INCORRECT_PASSWORD',

  // Validation
  VALIDATION_ERROR:        'VALIDATION_ERROR',
  INVALID_DATE:            'INVALID_DATE',

  // Resources
  HABIT_NOT_FOUND:         'HABIT_NOT_FOUND',
  HABIT_LOG_EXISTS:        'HABIT_LOG_EXISTS',
  RECOVERY_GOAL_NOT_FOUND: 'RECOVERY_GOAL_NOT_FOUND',
  JOURNAL_ENTRY_EXISTS:    'JOURNAL_ENTRY_EXISTS',
  NOTE_NOT_FOUND:          'NOTE_NOT_FOUND',
  FOLDER_NOT_FOUND:        'FOLDER_NOT_FOUND',
  FOLDER_DEPTH_EXCEEDED:   'FOLDER_DEPTH_EXCEEDED',
  WORKOUT_NOT_FOUND:       'WORKOUT_NOT_FOUND',
  EXERCISE_NOT_FOUND:      'EXERCISE_NOT_FOUND',
  GOAL_NOT_FOUND:          'GOAL_NOT_FOUND',
  MILESTONE_NOT_FOUND:     'MILESTONE_NOT_FOUND',

  // Limits
  HABIT_LIMIT_REACHED:     'HABIT_LIMIT_REACHED',
  NOTE_LIMIT_REACHED:      'NOTE_LIMIT_REACHED',
  GOAL_LIMIT_REACHED:      'GOAL_LIMIT_REACHED',

  // Access
  FORBIDDEN:               'FORBIDDEN',
  IMPERSONATION_DISABLED:  'IMPERSONATION_DISABLED',
  INSUFFICIENT_PERMISSIONS:'INSUFFICIENT_PERMISSIONS',

  // Storage
  FILE_TOO_LARGE:          'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE:   'UNSUPPORTED_FILE_TYPE',
  UPLOAD_FAILED:           'UPLOAD_FAILED',

  // Generic
  NOT_FOUND:               'NOT_FOUND',
  BAD_REQUEST:             'BAD_REQUEST',
  CONFLICT:                'CONFLICT',
  RATE_LIMITED:            'RATE_LIMITED',
  INTERNAL_ERROR:          'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
